BAD_WORD = 'хрен'
COUNT_POSTS_PAGINATE = 10
LENGHT_STRING = 256
MAX_QUANTITY_SYMBOLS = 40
FORMAT_DATE_TIME = '%Y-%m-%dT%H:%M:%S'
FROM_EMAIL = 'post_form@lst.net'
HEIGHT_COMMENT_FORM = 5
WIDTH_COMMENT_FORM = 10
